name: Deploy to cloud functions

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GEO_DB_PATH: ${{ secrets.GEO_DB_PATH }}
  IMAGE_STORAGE_PATH: ${{ secrets.IMAGE_STORAGE_PATH }}
  ADMIN_USERS: $${  secrets.ADMIN_USERS }}

jobs:
  deploy:
    name: Setup, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}


    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        make deploy
